FROM golang:1.23-alpine AS builder

WORKDIR /app

# Instala dependencias mínimas
RUN apk add --no-cache git

COPY . .

# Asegura que no se use glibc
ENV CGO_ENABLED=0 GOOS=linux GOARCH=amd64

RUN go mod tidy
RUN go build -o inventario ./cmd/api

# Imagen final ultra ligera
FROM alpine:3.18

WORKDIR /app

COPY --from=builder /app/inventario .

EXPOSE 8080

CMD ["./inventario"]